import random

# screen properties
WIDTH = 1300
HEIGHT = 700
WINDOW_DIMENSION = (WIDTH, HEIGHT)
FPS = 120




# game properties
BULLET_SPEED = 20
DEFAULT_PLAYER_SPEED = 7
SCREEN_OFFSET = 10
PLAYER_SHOOT_DELAY = 175
PLAYER_BURST_DELAY = 750
PLAYER_SCALE = 3 / 4
MOB_NUMBER = 20
STAR_NUMBER = 20

START_PLAYER_LIVES = 2
MAX_PLAYER_LIVES = 3
MIN_WEAPON = 1
MAX_WEAPON = 2

MIN_Y_SPAWN = -100
MAX_Y_SPAWN = -40

PIRATE_MAX_SPEED_X = 5
PIRATE_MIN_SPEED_Y = 5
PIRATE_MAX_SPEED_Y = 12


#HUD properties

BAR_LENGTH = 190
BAR_HEIGHT = 15
SCORE_LENGTH = 10

MOB_INIT_POSITION_LIST = [random.randrange(-300, -10) for x in range(0, 20)]